src/blueprint/blueprint.py
import time
from flask import Blueprint, request
from flask import render_template, url_for

import src.core.assessment as assessment


bp = Blueprint("date", __name__, url_prefix="")


@bp.app_context_processor
def cache_buster() -> dict:
    return {"cache_buster": time.time()}


@bp.route("/form", methods=["POST"])
def form() -> str:
    # Get the user's preferred locale, for use when interacting with Yelp
    request.json["locale"] = request.accept_languages.best.replace("-", "_")

    # Make an assessment regarding the user's date status
    result = assessment.make(request.json)
    responses = {
        "no": url_for("date.no"),
        "yes": url_for("date.yes"),
        "maybe": url_for("date.maybe"),
    }
    return responses[result]


@bp.route("/")
def index() -> str:
    return render_template("permission.html")


@bp.route("/privacy")
def privacy() -> str:
    return render_template("privacy.html", page_title="Privacy")


@bp.route("/no")
def no() -> str:
    return render_template("no.html", page_title="No.")


@bp.route("/maybe")
def maybe() -> str:
    return render_template("maybe.html", page_title="Maybe...?")


@bp.route("/yes")
def yes() -> str:
    return render_template("yes.html", page_title="Yes!")


@bp.app_errorhandler(404)
def page_not_found(e) -> str:
    return render_template("error.html", page_title="Status: Unavailable"), 404


@bp.app_errorhandler(500)
def internal_server_error(e) -> str:
    return render_template(
        "error.html",
        page_title="Status: Incapable of love"
    ), 500

src/main.py
from flask import Flask

from dotenv import dotenv_values, find_dotenv

from src.blueprint import blueprint
from src.extensions import init_extensions


def create_app():
    app = Flask(__name__)

    # Load the variables from the .env file into the app config
    env_vals = dotenv_values(find_dotenv())
    for key, value in env_vals.items():
        app.config[key] = (value if value != "" else None)

    # Load any extensions and register the blueprint
    init_extensions(app)
    app.register_blueprint(blueprint.bp)
    return app

src/templates/_hero-button.html
<h1 style="text-align: center;">
  <a href="{{ url_for('date.index') }}">Determine your date status</a>
</h1>

src/templates/_social.html
<meta name="theme-color" content="#b62828">
<link rel="shortcut icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico', time=cache_buster) }}">
<link rel="apple-touch-icon-precomposed" sizes="256x256" href="{{ url_for('static', filename='apple-touch-icon-precomposed.png') }}">
<meta name="title" content="Are You on a Date?">
<meta name="description" content="Determine if you are currently on a date!">

<meta property="og:site_name" content="date.codetri.net">
<meta property="og:type" content="website">
<meta property="og:title" content="Are You on a Date?">
<meta property="og:url" content="https://date.codetri.net">
<meta property="og:image" content="https://date.codetri.net{{ url_for('static', filename='social-media-card.png') }}">
<meta property="og:description" content="Determine if you are currently on a date!">

<meta name="twitter:card" content="summary_large_image">
<meta name="twitter:site" content="@cely717">
<meta name="twitter:creator" content="@cely717">
<meta name="twitter:title" content="Are You on a Date?">
<meta name="twitter:description" content="Determine if you are currently on a date!">
<meta name="twitter:image:src" content="https://date.codetri.net{{ url_for('static', filename='social-media-card.png') }}">

src/templates/analytics.html
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-49239721-3"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'UA-49239721-3');
</script>

src/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Are You on a Date? {{ page_title|default("") }}</title>
  {% include '_social.html' %}
  {% block noscript %}{% endblock %}
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=IBM+Plex+Serif:400,400i|Lobster+Two:400,700?display=swap">
  <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css', time=cache_buster) }}">
</head>

<body>
  <header>
    <img height="100" src="{{ url_for('static', filename='candle.png') }}" alt="">
    <h1><a href="{{ url_for('date.index') }}">Are You on a Date?</a></h1>
    <img height="100" src="{{ url_for('static', filename='candle.png') }}" alt="">
  </header>

  <main>
  {% block content %}{% endblock %}
  </main>

  <footer>
    <a href="{{ url_for('date.privacy') }}">Privacy Policy</a>
  </footer>

  {{ JSGlue.include() }}
  {% include "analytics.html" %}
  {%- block scripts %}{% endblock %}
  <script>
    // Add indicator class when lacking geolocation data
    // in in order to display messages that say that
    if (window.sessionStorage.getItem("location-denied")) {
      document.body.classList.add("no-geo");
      window.sessionStorage.removeItem("location-denied");
    }
  </script>
</body>
</html>

src/templates/error.html
{% extends 'base.html' %}

{% block content %}
<h2>Whops, that isn't right!</h2>
<p>It looks like there has been some form of an error. We don't think you were trying to be here. Sorry about that. Just keep on truckin' like you never saw this page comin'. 🚚</p>

{% include "_hero-button.html" %}
{% endblock %}

src/templates/forms/form-permission.html
<form id="form-permission" method="POST">
  <input type="hidden" name="csrf_token" id="csrf_token" value="{{ csrf_token() }}">
  <label>
    <input type="checkbox" name="college" id="college">
    Check this if you are a college student<br>
    <small>(We understand you're broke 😉)</small>
  </label>

  <label>
    <button type="button" name="permission-yes" id="permission-yes" value="yes">
      Yes, you may access my location<br>
      <small>(A dialog will appear after clicking this)</small>
    </button>
  </label>

  <label><button type="button" name="permission-no" id="permission-no" value="no">No, you may not access my location</button></label>
</form>

src/templates/maybe.html
{% extends 'base.html' %}

{% block content %}
<h2>Maybe&hellip;?</h2>
<p>It is possible that you are on a date but we are not positive about it. Complicating factors include:</p>
<ul>
  <li>The location of your date</li>
  <li>The quality (💲💲) of the date location</li>
  <li>Being a college student and only being able to have simple dates due to time and money</li>
  <li>Not having the person's explict word that is this indeed a date</li>
</ul>
<p>
  Just because we cannot figure out if you're on a date doesn't mean you are not on a date. We all make mistakes at times.
  If this really is a date, feel free to ignore us. Go ahead and enjoy your date. We won't bother you.
</p>

<div class="extra-msg">
  <h2>Sooooooo&hellip;</h2>
  <p>
    Because we are not sure that you are on a date, you could <a href="{{ url_for('date.index') }}">try again</a> and perhaps we'll get it right this time.
    If we're completely wrong and you actually are on a date, please accept our apology and a
    <a target="_blank" rel="nofollow noopener" href="https://le717.github.io/did-a-thing/?name=you">small token of our appreciation</a> for being on a date.
  </p>
</div>
{% endblock %}

src/templates/no.html
{% extends 'base.html' %}

{% block content %}
<h2>No.</h2>
<p>How was this determined? Quite simply, really. Try asking yourself the following questions:</p>
<ul>
  <li>Did you fail to previously arrange with the person for this to be a date?</li>
  <li>Did you ask someone who is not sitting at your table if this is a date?</li>
</ul>
<p>If you can answer "yes" to any one of questions, then you are not on a date. Sorry to break your heart like that. 💔</p>
<p>Also, if you just so happen to be at Taco Bell, you need to ask yourself what it is you are doing with your life by attempting to have a <em>date</em> at Taco Bell. 🤔</p>

<div class="geo-msg">
  <h2>By the way&hellip;</h2>
  <p>We were unable to access your current location, either because it's not supported on your device or you denied access. We are unable to assess your date status without it. If you would like us to actually perform the assesment, <a href="{{ url_for('date.index') }}">re-run the assessment</a> and permit access to your location. We promise not to misuse it.</p>
</div>
{% endblock %}

src/templates/permission.html
{% extends 'base.html' %}

{% block noscript %}
<noscript>
  <meta http-equiv="refresh" content="0; url={{ url_for('date.no') }}">
</noscript>
{% endblock %}

{% block content %}
<h2>Before we begin&hellip;</h2>
<p>In order to assess if you are on a date or not, we would like to have access to your current location. This will allow us to accurately assess your date status. You might consider reading our <a href="{{ url_for('date.privacy') }}">privacy policy</a> before continuing on (tl;dr: we don't want your info).</p>

{% include 'forms/form-permission.html' %}
{% endblock %}

{% block scripts %}
<script>
  "use strict";
  // We don't support the geolocation api in this browser :(
  if (!navigator.geolocation) {
    window.location = Flask.url_for("date.no");
  }
</script>
<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=fetch,Element.prototype.matches"></script>
<script src="{{ url_for('static', filename='js/script.js', time=cache_buster) }}"></script>
{% endblock %}

src/templates/privacy.html
{% extends 'base.html' %}
{% block content %}

<h2>Privacy Policy</h2>
<h3>tl;dr: We don't want your info</h3>
<p>Your privacy is valued. The result of this assessment are not shared with the creator or third-parties. Your current location is used solely to perform the assessment. The state of your dating life, regardless of sadness level, is strictly between you and anyone else looking at your screen right now.</p>

<p>Speaking of your current location, the only reason we request it is to make use of the <a target="_blank" rel="nofollow noopener noreferrer" href="https://www.yelp.com/">Yelp</a> <a target="_blank" rel="nofollow noopener noreferrer" href="https://www.yelp.com/developers">API</a> to determine where you are for the purpose of determining if you are on a date. That's it. We don't store it or give it to anyone. Pinky promise. If you are paranoid, you can view this site's <a target="_blank" rel="nofollow noopener" href="https://github.com/le717/areyouona-date">source code</a> and see for yourself.</p>

{% include "_hero-button.html" %}
{% endblock %}

src/templates/yes.html
{% extends 'base.html' %}

{% block content %}
<h2>Yes!</h2>
<p>At least, we think you are on a date. Your date status cannot be guaranteed except by you and the person you are with but we think we are right. Some congratulations are in order for going out to a nice place and not being a <a target="_blank" rel="nofollow noopener noreferrer" href="http://hanna-barbera.wikia.com/wiki/Cosmo_G._Spacely">penny-pinching cheapskate</a>. Enjoy the time together with your date person (or animal. We won't judge.). 🎊</p>

<div class="extra-msg">
  <h2>It's not worth mentioning, but&hellip;</h2>
  <p>If for some <em>weird</em> reason you have reason to believe that the assessment is in error regarding your date status or are in shock that you are actually on a really for real date, you can always <a href="{{ url_for('date.index') }}">run the assessment again</a> to confirm that you're still on a date. That being said, we don't know why you would do that. You are on a date. Just go with it and don't look a gifted horse in the mouth (whatever that saying means ¯\_(ツ)_/¯).</p>
</div>
{% endblock %}